// app/layout.tsx
import Header from "../app/components/Header";
import Footer from "./components/footer"; // Импортируем футер
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 flex flex-col min-h-screen`}>
        <Header />
        <main className="container mx-auto p-6 flex-grow">{children}</main> {/* Контент займет всю доступную высоту */}
        <Footer /> {/* Добавляем футер */}
      </body>
    </html>
  );
}
